# Generated by Django 6.0.6 on 2026-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
