# Generated by Django 6.0.6 on 2026-06-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_search_tags_product_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, default='temp', help_text='Unique Stock Keeping Unit for this product.', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
