# Generated by Django 6.0.6 on 2026-06-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
