# Generated by Django 6.0.6 on 2026-06-30 07:31

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='search_tags',
            field=models.TextField(blank=True, db_index=True, help_text='Comma-separated keywords for improving search.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Unique Stock Keeping Unit for this product.', max_length=150, unique=True),
        ),
    ]
